# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs Sampler
#' @description Generate a chain with Gibbs sampler.
#' @param N sample size
#' @return A matrix of random samples.
#'
#' 
#' @export
GibbsC <- function(N) {
    .Call('_StatComp21060_GibbsC', PACKAGE = 'StatComp21060', N)
}

