# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title bivariate MC chain
#' @description  bivariate MC chain
#' @param N sample size
#' @param n initial value
#' @param a sample size
#' @param b sample size
#' @return mat A matrix
#' @export
bi_chain_cpp <- function(N, n = 100L, a = 50L, b = 50L) {
    .Call('_StatComp21060_bi_chain_cpp', PACKAGE = 'StatComp21060', N, n, a, b)
}

